header:
  version: 11

machine: dogbonedark
distro: kiss
target:
  - kiss-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.8"
    layers:
      .: disabled

  openembedded-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: scarthgap
    layers:
      meta:

  meta-arm:
    url: "git://git.yoctoproject.org/meta-arm"
    branch: scarthgap
    layers:
      meta-arm-toolchain:
      meta-arm:

  meta-kiss:
    layers:
      meta-kiss:

local_conf_header:
  meta-kiss: |
    # Some useful lines you may want to copy to your site.conf for development
    # INHERIT += "rm_work"
    # EXTRA_IMAGE_FEATURES += "empty-root-password \
    #                          allow-empty-password \
    #                          allow-root-login \
    #                          "
